### ISSUE TITLE
width of the cards is larger than desired ,doesn't look good at BestSeller 

### ISSUE THREAD

**Issue by Avyakta000** [BaoiamApp/Divueens_Frontend#33]
![Screenshot 2024-07-01 164011](https://github.com/BaoiamApp/Divueens_Frontend/assets/100035215/a8e9b649-ca36-47a0-95f6-f4be26b92f63)
it should look like this

**Comment by BaoiamApp** [comment]
It has been redesigned.

**Comment by Avyakta000** [comment]
If its final then slider logic needs to be changed since on large screens cards at the end are not vislible properly as we slide through it.

  *
To fix that issue down here instead of 210 , 310 could be added (because of newly added width) at BestSeller.jsx at line 48. (const imagesToShow = Math.floor((screenWidth - 240) / 210); //extra(140,100,10) -100 for margin each image takes approximately 200px, )
  *
Also at line 158 "div " element with no class should be removed because of that card-information is not aligned at center.
  *


I dont know how did these issues arrise at the time of pull request everything was alright.

Regards,
Himanshu

________________________________
